
LocationPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/location_solver.json"
ScenarioPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/scenario_solver.json"
PlanPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/plan.json"
Mode: "DeepLook" #Standard or DeepLook


TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5
  SuppressConsoleOutput: false

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  SuppressConsoleOutput: false
  IintensifyOnImprovement: false

DeepLook:
  Path: "../../C++/hello"
  Mode: "EVAL" #EVAL_AND_STORE
  PathLocation: "./PathLocation"
  PathScenario: "./PathScenario"
  PathPlan: "./PathPlan"
  PlanType: "Solver"
  PathScenarioEval: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look"