
LocationPath: "./database/TUSS-Instance-Generator/featured/fixed_location/instandingTest/location_kleineBinckhorst_HIP_dump.json"
ScenarioPath: "./database/TUSS-Instance-Generator/featured/fixed_location/instandingTest/scenario_instandingTest_hip.json"
PlanPath: "./database/TUSS-Instance-Generator/featured/fixed_location/instandingTest/plan_scenario_instandingTest_hip.json"

TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5
  SuppressConsoleOutput: false

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  SuppressConsoleOutput: false
  IintensifyOnImprovement: false