
LocationPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/location_solver.json"
ScenarioPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/scenario_solver.json"
PlanPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/plan.json"
Mode: "DeepLook" #Standard or DeepLook


TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5
  SuppressConsoleOutput: false

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  SuppressConsoleOutput: false
  IintensifyOnImprovement: false
DeepLook:
  Path: "/workspace/robust-rail-evaluator/build/TORS" #../../C++/hello"
  Mode: "EVAL_AND_STORE" #EVAL_AND_STORE or EVAL
  PathLocation: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_deep_look"
  PathScenario: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/scenario_evaluator.json"
  PathPlan: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/plan.json"
  PlanType: "Solver"
  PathEvalResult: /workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_deep_look/Evaluation_Results.txt"
  PathScenarioEval: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_deep_look"