// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Plan.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlgoIface {

  /// <summary>Holder for reflection information generated from Plan.proto</summary>
  public static partial class PlanReflection {

    #region Descriptor
    /// <summary>File descriptor for Plan.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpQbGFuLnByb3RvEgphbGdvX2lmYWNlGg5Mb2NhdGlvbi5wcm90bxoOU2Nl",
            "bmFyaW8ucHJvdG8iVgoEUGxhbhIjCgdhY3Rpb25zGAEgAygLMhIuYWxnb19p",
            "ZmFjZS5BY3Rpb24SKQoKdHJhY2tQYXJ0cxgCIAMoCzIVLmFsZ29faWZhY2Uu",
            "VHJhY2tQYXJ0ItUBCgZBY3Rpb24SEQoJc3RhcnRUaW1lGAEgASgEEg8KB2Vu",
            "ZFRpbWUYAiABKAQSJgoIdGFza1R5cGUYAyABKAsyFC5hbGdvX2lmYWNlLlRh",
            "c2tUeXBlEi4KDHNodW50aW5nVW5pdBgEIAEoCzIYLmFsZ29faWZhY2UuU2h1",
            "bnRpbmdVbml0EhAKCGxvY2F0aW9uGAUgASgEEicKCXJlc291cmNlcxgGIAMo",
            "CzIULmFsZ29faWZhY2UuUmVzb3VyY2USFAoMdHJhaW5Vbml0SWRzGAcgAygJ",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AlgoIface.LocationReflection.Descriptor, global::AlgoIface.ScenarioReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AlgoIface.Plan), global::AlgoIface.Plan.Parser, new[]{ "Actions", "TrackParts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlgoIface.Action), global::AlgoIface.Action.Parser, new[]{ "StartTime", "EndTime", "TaskType", "ShuntingUnit", "Location", "Resources", "TrainUnitIds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// This message contains the result of a shunting algorithm.
  /// </summary>
  public sealed partial class Plan : pb::IMessage<Plan>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Plan> _parser = new pb::MessageParser<Plan>(() => new Plan());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Plan> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlgoIface.PlanReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan(Plan other) : this() {
      actions_ = other.actions_.Clone();
      trackParts_ = other.trackParts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan Clone() {
      return new Plan(this);
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AlgoIface.Action> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(10, global::AlgoIface.Action.Parser);
    private readonly pbc::RepeatedField<global::AlgoIface.Action> actions_ = new pbc::RepeatedField<global::AlgoIface.Action>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AlgoIface.Action> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "trackParts" field.</summary>
    public const int TrackPartsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::AlgoIface.TrackPart> _repeated_trackParts_codec
        = pb::FieldCodec.ForMessage(18, global::AlgoIface.TrackPart.Parser);
    private readonly pbc::RepeatedField<global::AlgoIface.TrackPart> trackParts_ = new pbc::RepeatedField<global::AlgoIface.TrackPart>();
    /// <summary>
    /// A list of all TrackParts. From this a rail graph can be constructed.
    /// This field should be temporary and be replaced as soon as we send input to the algorithm.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AlgoIface.TrackPart> TrackParts {
      get { return trackParts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Plan);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Plan other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!actions_.Equals(other.actions_)) return false;
      if(!trackParts_.Equals(other.trackParts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= actions_.GetHashCode();
      hash ^= trackParts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      actions_.WriteTo(output, _repeated_actions_codec);
      trackParts_.WriteTo(output, _repeated_trackParts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      actions_.WriteTo(ref output, _repeated_actions_codec);
      trackParts_.WriteTo(ref output, _repeated_trackParts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += actions_.CalculateSize(_repeated_actions_codec);
      size += trackParts_.CalculateSize(_repeated_trackParts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Plan other) {
      if (other == null) {
        return;
      }
      actions_.Add(other.actions_);
      trackParts_.Add(other.trackParts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 18: {
            trackParts_.AddEntriesFrom(input, _repeated_trackParts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            actions_.AddEntriesFrom(ref input, _repeated_actions_codec);
            break;
          }
          case 18: {
            trackParts_.AddEntriesFrom(ref input, _repeated_trackParts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Action : pb::IMessage<Action>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Action> _parser = new pb::MessageParser<Action>(() => new Action());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Action> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlgoIface.PlanReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Action() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Action(Action other) : this() {
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      taskType_ = other.taskType_ != null ? other.taskType_.Clone() : null;
      shuntingUnit_ = other.shuntingUnit_ != null ? other.shuntingUnit_.Clone() : null;
      location_ = other.location_;
      resources_ = other.resources_.Clone();
      trainUnitIds_ = other.trainUnitIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Action Clone() {
      return new Action(this);
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 1;
    private ulong startTime_;
    /// <summary>
    /// The time interval of this action.
    /// Times are in seconds since the epoch.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 2;
    private ulong endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "taskType" field.</summary>
    public const int TaskTypeFieldNumber = 3;
    private global::AlgoIface.TaskType taskType_;
    /// <summary>
    /// The type of this action (e.g. cleaning, moving, waiting)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AlgoIface.TaskType TaskType {
      get { return taskType_; }
      set {
        taskType_ = value;
      }
    }

    /// <summary>Field number for the "shuntingUnit" field.</summary>
    public const int ShuntingUnitFieldNumber = 4;
    private global::AlgoIface.ShuntingUnit shuntingUnit_;
    /// <summary>
    /// The ShuntingUnit to which this Action applies
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AlgoIface.ShuntingUnit ShuntingUnit {
      get { return shuntingUnit_; }
      set {
        shuntingUnit_ = value;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 5;
    private ulong location_;
    /// <summary>
    /// The TrackPart ID on which this Action occurs.
    /// If taskType = Move, then trackPart specifies the move destination,
    /// and the resources specify the path.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::AlgoIface.Resource> _repeated_resources_codec
        = pb::FieldCodec.ForMessage(50, global::AlgoIface.Resource.Parser);
    private readonly pbc::RepeatedField<global::AlgoIface.Resource> resources_ = new pbc::RepeatedField<global::AlgoIface.Resource>();
    /// <summary>
    /// Other resources besides the TrackPart involved with the Action.
    /// For example for taskType = InternalCleaning there could be
    /// a CleaningPlatform Facility Resource.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AlgoIface.Resource> Resources {
      get { return resources_; }
    }

    /// <summary>Field number for the "trainUnitIds" field.</summary>
    public const int TrainUnitIdsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_trainUnitIds_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> trainUnitIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Train units involved in this Action
    /// If not specified, all train units are involved.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TrainUnitIds {
      get { return trainUnitIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Action);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Action other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (!object.Equals(TaskType, other.TaskType)) return false;
      if (!object.Equals(ShuntingUnit, other.ShuntingUnit)) return false;
      if (Location != other.Location) return false;
      if(!resources_.Equals(other.resources_)) return false;
      if(!trainUnitIds_.Equals(other.trainUnitIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StartTime != 0UL) hash ^= StartTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (taskType_ != null) hash ^= TaskType.GetHashCode();
      if (shuntingUnit_ != null) hash ^= ShuntingUnit.GetHashCode();
      if (Location != 0UL) hash ^= Location.GetHashCode();
      hash ^= resources_.GetHashCode();
      hash ^= trainUnitIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartTime != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(EndTime);
      }
      if (taskType_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TaskType);
      }
      if (shuntingUnit_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ShuntingUnit);
      }
      if (Location != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Location);
      }
      resources_.WriteTo(output, _repeated_resources_codec);
      trainUnitIds_.WriteTo(output, _repeated_trainUnitIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartTime != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(EndTime);
      }
      if (taskType_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TaskType);
      }
      if (shuntingUnit_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ShuntingUnit);
      }
      if (Location != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Location);
      }
      resources_.WriteTo(ref output, _repeated_resources_codec);
      trainUnitIds_.WriteTo(ref output, _repeated_trainUnitIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (taskType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TaskType);
      }
      if (shuntingUnit_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShuntingUnit);
      }
      if (Location != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Location);
      }
      size += resources_.CalculateSize(_repeated_resources_codec);
      size += trainUnitIds_.CalculateSize(_repeated_trainUnitIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Action other) {
      if (other == null) {
        return;
      }
      if (other.StartTime != 0UL) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.taskType_ != null) {
        if (taskType_ == null) {
          TaskType = new global::AlgoIface.TaskType();
        }
        TaskType.MergeFrom(other.TaskType);
      }
      if (other.shuntingUnit_ != null) {
        if (shuntingUnit_ == null) {
          ShuntingUnit = new global::AlgoIface.ShuntingUnit();
        }
        ShuntingUnit.MergeFrom(other.ShuntingUnit);
      }
      if (other.Location != 0UL) {
        Location = other.Location;
      }
      resources_.Add(other.resources_);
      trainUnitIds_.Add(other.trainUnitIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 16: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 26: {
            if (taskType_ == null) {
              TaskType = new global::AlgoIface.TaskType();
            }
            input.ReadMessage(TaskType);
            break;
          }
          case 34: {
            if (shuntingUnit_ == null) {
              ShuntingUnit = new global::AlgoIface.ShuntingUnit();
            }
            input.ReadMessage(ShuntingUnit);
            break;
          }
          case 40: {
            Location = input.ReadUInt64();
            break;
          }
          case 50: {
            resources_.AddEntriesFrom(input, _repeated_resources_codec);
            break;
          }
          case 58: {
            trainUnitIds_.AddEntriesFrom(input, _repeated_trainUnitIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 16: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 26: {
            if (taskType_ == null) {
              TaskType = new global::AlgoIface.TaskType();
            }
            input.ReadMessage(TaskType);
            break;
          }
          case 34: {
            if (shuntingUnit_ == null) {
              ShuntingUnit = new global::AlgoIface.ShuntingUnit();
            }
            input.ReadMessage(ShuntingUnit);
            break;
          }
          case 40: {
            Location = input.ReadUInt64();
            break;
          }
          case 50: {
            resources_.AddEntriesFrom(ref input, _repeated_resources_codec);
            break;
          }
          case 58: {
            trainUnitIds_.AddEntriesFrom(ref input, _repeated_trainUnitIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
