// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TrainUnitTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AlgoIfaceEvaluator {

  /// <summary>Holder for reflection information generated from TrainUnitTypes.proto</summary>
  public static partial class TrainUnitTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for TrainUnitTypes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrainUnitTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRUcmFpblVuaXRUeXBlcy5wcm90bxIUYWxnb19pZmFjZV9ldmFsdWF0b3Ii",
            "tAIKDVRyYWluVW5pdFR5cGUSEwoLZGlzcGxheU5hbWUYASABKAkSEQoJY2Fy",
            "cmlhZ2VzGAIgASgNEg4KBmxlbmd0aBgEIAEoARIXCg9jb21iaW5lRHVyYXRp",
            "b24YBSABKAQSFQoNc3BsaXREdXJhdGlvbhgGIAEoBBIUCgxiYWNrTm9ybVRp",
            "bWUYByABKAQSGAoQYmFja0FkZGl0aW9uVGltZRgIIAEoBBITCgt0cmF2ZWxT",
            "cGVlZBgJIAEoBBITCgtzdGFydFVwVGltZRgKIAEoBBISCgp0eXBlUHJlZml4",
            "GAsgASgJEhEKCW5lZWRzTG9jbxgMIAEoCBIOCgZpc0xvY28YDSABKAgSGAoQ",
            "bmVlZHNFbGVjdHJpY2l0eRgOIAEoCBIQCghpZFByZWZpeBgPIAEoBSJECg5U",
            "cmFpblVuaXRUeXBlcxIyCgV0eXBlcxgBIAMoCzIjLmFsZ29faWZhY2VfZXZh",
            "bHVhdG9yLlRyYWluVW5pdFR5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AlgoIfaceEvaluator.TrainUnitType), global::AlgoIfaceEvaluator.TrainUnitType.Parser, new[]{ "DisplayName", "Carriages", "Length", "CombineDuration", "SplitDuration", "BackNormTime", "BackAdditionTime", "TravelSpeed", "StartUpTime", "TypePrefix", "NeedsLoco", "IsLoco", "NeedsElectricity", "IdPrefix" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AlgoIfaceEvaluator.TrainUnitTypes), global::AlgoIfaceEvaluator.TrainUnitTypes.Parser, new[]{ "Types_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// TrainUnitType is a type of train unit
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TrainUnitType : pb::IMessage<TrainUnitType>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainUnitType> _parser = new pb::MessageParser<TrainUnitType>(() => new TrainUnitType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainUnitType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlgoIfaceEvaluator.TrainUnitTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitType(TrainUnitType other) : this() {
      displayName_ = other.displayName_;
      carriages_ = other.carriages_;
      length_ = other.length_;
      combineDuration_ = other.combineDuration_;
      splitDuration_ = other.splitDuration_;
      backNormTime_ = other.backNormTime_;
      backAdditionTime_ = other.backAdditionTime_;
      travelSpeed_ = other.travelSpeed_;
      startUpTime_ = other.startUpTime_;
      typePrefix_ = other.typePrefix_;
      needsLoco_ = other.needsLoco_;
      isLoco_ = other.isLoco_;
      needsElectricity_ = other.needsElectricity_;
      idPrefix_ = other.idPrefix_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitType Clone() {
      return new TrainUnitType(this);
    }

    /// <summary>Field number for the "displayName" field.</summary>
    public const int DisplayNameFieldNumber = 1;
    private string displayName_ = "";
    /// <summary>
    /// Name of the train unit type
    /// For example, "SGM" or "SLT".
    /// Currently, this is "SLT4" or "SLT6", see 'typeprefix' later on. #warning
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "carriages" field.</summary>
    public const int CarriagesFieldNumber = 2;
    private uint carriages_;
    /// <summary>
    /// Number of carriages. This is the total number of carriages,
    /// including the first and last carriage.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Carriages {
      get { return carriages_; }
      set {
        carriages_ = value;
      }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 4;
    private double length_;
    /// <summary>
    /// Length of this train unit, in meters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    /// <summary>Field number for the "combineDuration" field.</summary>
    public const int CombineDurationFieldNumber = 5;
    private ulong combineDuration_;
    /// <summary>
    /// Time it takes to perform a combine in seconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CombineDuration {
      get { return combineDuration_; }
      set {
        combineDuration_ = value;
      }
    }

    /// <summary>Field number for the "splitDuration" field.</summary>
    public const int SplitDurationFieldNumber = 6;
    private ulong splitDuration_;
    /// <summary>
    /// Time it takes to perform a split in seconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SplitDuration {
      get { return splitDuration_; }
      set {
        splitDuration_ = value;
      }
    }

    /// <summary>Field number for the "backNormTime" field.</summary>
    public const int BackNormTimeFieldNumber = 7;
    private ulong backNormTime_;
    /// <summary>
    /// kopmaaktijd = backNormTime + #carriage * backAdditionTime
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BackNormTime {
      get { return backNormTime_; }
      set {
        backNormTime_ = value;
      }
    }

    /// <summary>Field number for the "backAdditionTime" field.</summary>
    public const int BackAdditionTimeFieldNumber = 8;
    private ulong backAdditionTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BackAdditionTime {
      get { return backAdditionTime_; }
      set {
        backAdditionTime_ = value;
      }
    }

    /// <summary>Field number for the "travelSpeed" field.</summary>
    public const int TravelSpeedFieldNumber = 9;
    private ulong travelSpeed_;
    /// <summary>
    /// this is the speed of the train but that is yet to be determinded wether that is here or location specific #warning
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TravelSpeed {
      get { return travelSpeed_; }
      set {
        travelSpeed_ = value;
      }
    }

    /// <summary>Field number for the "startUpTime" field.</summary>
    public const int StartUpTimeFieldNumber = 10;
    private ulong startUpTime_;
    /// <summary>
    /// Startup + Shutdown
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong StartUpTime {
      get { return startUpTime_; }
      set {
        startUpTime_ = value;
      }
    }

    /// <summary>Field number for the "typePrefix" field.</summary>
    public const int TypePrefixFieldNumber = 11;
    private string typePrefix_ = "";
    /// <summary>
    /// for example: "SLT" or "VIRM"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TypePrefix {
      get { return typePrefix_; }
      set {
        typePrefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "needsLoco" field.</summary>
    public const int NeedsLocoFieldNumber = 12;
    private bool needsLoco_;
    /// <summary>
    /// This TrainUnitType needs a locomotive, e.g. it cannot drive itself
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NeedsLoco {
      get { return needsLoco_; }
      set {
        needsLoco_ = value;
      }
    }

    /// <summary>Field number for the "isLoco" field.</summary>
    public const int IsLocoFieldNumber = 13;
    private bool isLoco_;
    /// <summary>
    /// Can pull/push other wagons
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsLoco {
      get { return isLoco_; }
      set {
        isLoco_ = value;
      }
    }

    /// <summary>Field number for the "needsElectricity" field.</summary>
    public const int NeedsElectricityFieldNumber = 14;
    private bool needsElectricity_;
    /// <summary>
    /// This train needs electricity, so it can only drive on electrified trackparts
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NeedsElectricity {
      get { return needsElectricity_; }
      set {
        needsElectricity_ = value;
      }
    }

    /// <summary>Field number for the "idPrefix" field.</summary>
    public const int IdPrefixFieldNumber = 15;
    private int idPrefix_;
    /// <summary>
    /// Prefix of train IDs of this type (i.e., the last two digits are removed)
    /// For example, for SLT4 this is 24
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdPrefix {
      get { return idPrefix_; }
      set {
        idPrefix_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainUnitType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainUnitType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DisplayName != other.DisplayName) return false;
      if (Carriages != other.Carriages) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Length, other.Length)) return false;
      if (CombineDuration != other.CombineDuration) return false;
      if (SplitDuration != other.SplitDuration) return false;
      if (BackNormTime != other.BackNormTime) return false;
      if (BackAdditionTime != other.BackAdditionTime) return false;
      if (TravelSpeed != other.TravelSpeed) return false;
      if (StartUpTime != other.StartUpTime) return false;
      if (TypePrefix != other.TypePrefix) return false;
      if (NeedsLoco != other.NeedsLoco) return false;
      if (IsLoco != other.IsLoco) return false;
      if (NeedsElectricity != other.NeedsElectricity) return false;
      if (IdPrefix != other.IdPrefix) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (Carriages != 0) hash ^= Carriages.GetHashCode();
      if (Length != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Length);
      if (CombineDuration != 0UL) hash ^= CombineDuration.GetHashCode();
      if (SplitDuration != 0UL) hash ^= SplitDuration.GetHashCode();
      if (BackNormTime != 0UL) hash ^= BackNormTime.GetHashCode();
      if (BackAdditionTime != 0UL) hash ^= BackAdditionTime.GetHashCode();
      if (TravelSpeed != 0UL) hash ^= TravelSpeed.GetHashCode();
      if (StartUpTime != 0UL) hash ^= StartUpTime.GetHashCode();
      if (TypePrefix.Length != 0) hash ^= TypePrefix.GetHashCode();
      if (NeedsLoco != false) hash ^= NeedsLoco.GetHashCode();
      if (IsLoco != false) hash ^= IsLoco.GetHashCode();
      if (NeedsElectricity != false) hash ^= NeedsElectricity.GetHashCode();
      if (IdPrefix != 0) hash ^= IdPrefix.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DisplayName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DisplayName);
      }
      if (Carriages != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Carriages);
      }
      if (Length != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Length);
      }
      if (CombineDuration != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(CombineDuration);
      }
      if (SplitDuration != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(SplitDuration);
      }
      if (BackNormTime != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(BackNormTime);
      }
      if (BackAdditionTime != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(BackAdditionTime);
      }
      if (TravelSpeed != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(TravelSpeed);
      }
      if (StartUpTime != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(StartUpTime);
      }
      if (TypePrefix.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(TypePrefix);
      }
      if (NeedsLoco != false) {
        output.WriteRawTag(96);
        output.WriteBool(NeedsLoco);
      }
      if (IsLoco != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsLoco);
      }
      if (NeedsElectricity != false) {
        output.WriteRawTag(112);
        output.WriteBool(NeedsElectricity);
      }
      if (IdPrefix != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(IdPrefix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DisplayName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DisplayName);
      }
      if (Carriages != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Carriages);
      }
      if (Length != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Length);
      }
      if (CombineDuration != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(CombineDuration);
      }
      if (SplitDuration != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(SplitDuration);
      }
      if (BackNormTime != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(BackNormTime);
      }
      if (BackAdditionTime != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(BackAdditionTime);
      }
      if (TravelSpeed != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(TravelSpeed);
      }
      if (StartUpTime != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(StartUpTime);
      }
      if (TypePrefix.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(TypePrefix);
      }
      if (NeedsLoco != false) {
        output.WriteRawTag(96);
        output.WriteBool(NeedsLoco);
      }
      if (IsLoco != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsLoco);
      }
      if (NeedsElectricity != false) {
        output.WriteRawTag(112);
        output.WriteBool(NeedsElectricity);
      }
      if (IdPrefix != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(IdPrefix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (Carriages != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Carriages);
      }
      if (Length != 0D) {
        size += 1 + 8;
      }
      if (CombineDuration != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CombineDuration);
      }
      if (SplitDuration != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SplitDuration);
      }
      if (BackNormTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BackNormTime);
      }
      if (BackAdditionTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BackAdditionTime);
      }
      if (TravelSpeed != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TravelSpeed);
      }
      if (StartUpTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartUpTime);
      }
      if (TypePrefix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TypePrefix);
      }
      if (NeedsLoco != false) {
        size += 1 + 1;
      }
      if (IsLoco != false) {
        size += 1 + 1;
      }
      if (NeedsElectricity != false) {
        size += 1 + 1;
      }
      if (IdPrefix != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdPrefix);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainUnitType other) {
      if (other == null) {
        return;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.Carriages != 0) {
        Carriages = other.Carriages;
      }
      if (other.Length != 0D) {
        Length = other.Length;
      }
      if (other.CombineDuration != 0UL) {
        CombineDuration = other.CombineDuration;
      }
      if (other.SplitDuration != 0UL) {
        SplitDuration = other.SplitDuration;
      }
      if (other.BackNormTime != 0UL) {
        BackNormTime = other.BackNormTime;
      }
      if (other.BackAdditionTime != 0UL) {
        BackAdditionTime = other.BackAdditionTime;
      }
      if (other.TravelSpeed != 0UL) {
        TravelSpeed = other.TravelSpeed;
      }
      if (other.StartUpTime != 0UL) {
        StartUpTime = other.StartUpTime;
      }
      if (other.TypePrefix.Length != 0) {
        TypePrefix = other.TypePrefix;
      }
      if (other.NeedsLoco != false) {
        NeedsLoco = other.NeedsLoco;
      }
      if (other.IsLoco != false) {
        IsLoco = other.IsLoco;
      }
      if (other.NeedsElectricity != false) {
        NeedsElectricity = other.NeedsElectricity;
      }
      if (other.IdPrefix != 0) {
        IdPrefix = other.IdPrefix;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DisplayName = input.ReadString();
            break;
          }
          case 16: {
            Carriages = input.ReadUInt32();
            break;
          }
          case 33: {
            Length = input.ReadDouble();
            break;
          }
          case 40: {
            CombineDuration = input.ReadUInt64();
            break;
          }
          case 48: {
            SplitDuration = input.ReadUInt64();
            break;
          }
          case 56: {
            BackNormTime = input.ReadUInt64();
            break;
          }
          case 64: {
            BackAdditionTime = input.ReadUInt64();
            break;
          }
          case 72: {
            TravelSpeed = input.ReadUInt64();
            break;
          }
          case 80: {
            StartUpTime = input.ReadUInt64();
            break;
          }
          case 90: {
            TypePrefix = input.ReadString();
            break;
          }
          case 96: {
            NeedsLoco = input.ReadBool();
            break;
          }
          case 104: {
            IsLoco = input.ReadBool();
            break;
          }
          case 112: {
            NeedsElectricity = input.ReadBool();
            break;
          }
          case 120: {
            IdPrefix = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DisplayName = input.ReadString();
            break;
          }
          case 16: {
            Carriages = input.ReadUInt32();
            break;
          }
          case 33: {
            Length = input.ReadDouble();
            break;
          }
          case 40: {
            CombineDuration = input.ReadUInt64();
            break;
          }
          case 48: {
            SplitDuration = input.ReadUInt64();
            break;
          }
          case 56: {
            BackNormTime = input.ReadUInt64();
            break;
          }
          case 64: {
            BackAdditionTime = input.ReadUInt64();
            break;
          }
          case 72: {
            TravelSpeed = input.ReadUInt64();
            break;
          }
          case 80: {
            StartUpTime = input.ReadUInt64();
            break;
          }
          case 90: {
            TypePrefix = input.ReadString();
            break;
          }
          case 96: {
            NeedsLoco = input.ReadBool();
            break;
          }
          case 104: {
            IsLoco = input.ReadBool();
            break;
          }
          case 112: {
            NeedsElectricity = input.ReadBool();
            break;
          }
          case 120: {
            IdPrefix = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TrainUnitTypes : pb::IMessage<TrainUnitTypes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainUnitTypes> _parser = new pb::MessageParser<TrainUnitTypes>(() => new TrainUnitTypes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainUnitTypes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AlgoIfaceEvaluator.TrainUnitTypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitTypes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitTypes(TrainUnitTypes other) : this() {
      types_ = other.types_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainUnitTypes Clone() {
      return new TrainUnitTypes(this);
    }

    /// <summary>Field number for the "types" field.</summary>
    public const int Types_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::AlgoIfaceEvaluator.TrainUnitType> _repeated_types_codec
        = pb::FieldCodec.ForMessage(10, global::AlgoIfaceEvaluator.TrainUnitType.Parser);
    private readonly pbc::RepeatedField<global::AlgoIfaceEvaluator.TrainUnitType> types_ = new pbc::RepeatedField<global::AlgoIfaceEvaluator.TrainUnitType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AlgoIfaceEvaluator.TrainUnitType> Types_ {
      get { return types_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainUnitTypes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainUnitTypes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!types_.Equals(other.types_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= types_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      types_.WriteTo(output, _repeated_types_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      types_.WriteTo(ref output, _repeated_types_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += types_.CalculateSize(_repeated_types_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainUnitTypes other) {
      if (other == null) {
        return;
      }
      types_.Add(other.types_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            types_.AddEntriesFrom(input, _repeated_types_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            types_.AddEntriesFrom(ref input, _repeated_types_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
